# Generated by Django 2.1.1 on 2018-10-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, default=None, unique=True)),
                ('name', models.CharField(help_text='The DApp name', max_length=30, unique=True)),
                ('author', models.CharField(help_text='The DApp author', max_length=150)),
                ('email', models.EmailField(help_text='Email of the primary contact (this will not be made public）', max_length=150)),
                ('short_text', models.CharField(help_text='A short teaser that is simple and descriptive', max_length=200)),
                ('text', models.TextField(help_text='The full description of your event')),
                ('website_url', models.URLField(help_text="A URL to this DApp's website")),
                ('contact_address', models.CharField(help_text='TRON account address', max_length=200)),
                ('software_license', models.CharField(help_text='(e.g. MIT, GPL)', max_length=50)),
                ('github', models.CharField(blank=True, help_text='Social Media Link', max_length=200)),
                ('launch_url', models.URLField(help_text='A URL that will launch this ÐApp directly')),
                ('logo_url', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ItemCategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ItemStatus'),
        ),
    ]
